[package]
name = "collisions"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
geom = { path = "../geom" }
kml = { path = "../kml" }
log = "0.4.14"
serde = "1.0.123"
